// <auto-generated />
namespace MathMasters.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class April24v2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(April24v2));
        
        string IMigrationMetadata.Id
        {
            get { return "202104241940054_April24v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
