// <auto-generated />
namespace MathMasters.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class May1v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(May1v1));
        
        string IMigrationMetadata.Id
        {
            get { return "202105012114184_May1v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
