// <auto-generated />
namespace MathMasters.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Apr28v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Apr28v1));
        
        string IMigrationMetadata.Id
        {
            get { return "202104290126514_Apr28v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
